// Builds content/places.yaml: the real towns and cities flagship clubs are based in (GDD v1.14).
// The world is real, so clubs belong to real places; only their nicknames are invented.
//
// Source: GeoNames, the same project the land borders come from.
//   https://download.geonames.org/export/dump/cities1000.zip   (populated places, 1,000+ people)
//   https://download.geonames.org/export/dump/countryInfo.txt  (country codes and capitals)
// Usage: npx tsx scripts/build-places.ts <cities1000.txt> <countryInfo.txt>
//
// Each market gets its largest populated places, biggest first. Neighbourhoods, historical,
// abandoned and destroyed places are left out. A market with no place in the file gets its
// capital from countryInfo. England, Scotland, Wales and Northern Ireland are split from the
// United Kingdom by GeoNames' first-level divisions.

import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";

const MAX_PLACES = 24;
const OUT = "content/places.yaml";
const RETRIEVED = new Date().toISOString().slice(0, 10);

/** Market id → GeoNames country code (and first-level division) where the names differ. */
const OVERRIDES: Record<string, { code: string; admin1?: string }> = {
  "chinese-taipei": { code: "TW" },
  congo: { code: "CG" },
  "dr-congo": { code: "CD" },
  england: { code: "GB", admin1: "ENG" },
  macau: { code: "MO" },
  netherlands: { code: "NL" },
  "northern-ireland": { code: "GB", admin1: "NIR" },
  "republic-of-ireland": { code: "IE" },
  scotland: { code: "GB", admin1: "SCT" },
  tahiti: { code: "PF" },
  "timor-leste": { code: "TL" },
  "us-virgin-islands": { code: "VI" },
  wales: { code: "GB", admin1: "WLS" },
};
const EXCLUDED_FEATURES = new Set(["PPLX", "PPLH", "PPLQ", "PPLW", "PPLCH"]);

const [citiesPath, infoPath] = process.argv.slice(2);
if (!citiesPath || !infoPath) {
  console.error("Usage: npx tsx scripts/build-places.ts <cities1000.txt> <countryInfo.txt>");
  process.exit(1);
}

const names = parse(readFileSync("content/names.yaml", "utf8")).countries as Record<string, string>;

const byName = new Map<string, string>();
const capitals = new Map<string, string>();
for (const line of readFileSync(infoPath, "utf8").split("\n")) {
  if (line.startsWith("#") || line.trim() === "") continue;
  const fields = line.split("\t");
  const code = fields[0] ?? "";
  byName.set((fields[4] ?? "").toLowerCase(), code);
  if (fields[5]) capitals.set(code, fields[5]);
}

interface Place {
  name: string;
  population: number;
}
const places = new Map<string, Place[]>();
for (const line of readFileSync(citiesPath, "utf8").split("\n")) {
  if (line.trim() === "") continue;
  const f = line.split("\t");
  if (f[6] !== "P" || EXCLUDED_FEATURES.has(f[7] ?? "")) continue;
  const key = `${f[8]}/${f[10]}`;
  const list = places.get(key) ?? [];
  list.push({ name: f[1] ?? "", population: Number(f[14] ?? 0) });
  places.set(key, list);
}

function placesFor(code: string, admin1?: string): Place[] {
  const found: Place[] = [];
  for (const [key, list] of places) {
    const [country, division] = key.split("/");
    if (country === code && (admin1 === undefined || division === admin1)) found.push(...list);
  }
  // One entry per name: the most populous place of that name.
  const best = new Map<string, Place>();
  for (const place of found) {
    const current = best.get(place.name);
    if (!current || place.population > current.population) best.set(place.name, place);
  }
  return [...best.values()]
    .filter((place) => place.population > 0)
    .sort((a, b) => b.population - a.population || a.name.localeCompare(b.name))
    .slice(0, MAX_PLACES);
}

const lines: string[] = [
  "# Real towns and cities where flagship clubs are based (GDD v1.14). Generated by",
  "# scripts/build-places.ts from GeoNames populated places (cities1000) and countryInfo; do not",
  "# hand-edit. Each market lists its largest places, biggest first, with GeoNames populations used",
  "# only to weight where clubs form. A market with no place in the file has its capital alone.",
  `# Retrieved ${RETRIEVED}. See sources.yaml (geonames-places).`,
  "",
  "places:",
];
const quote = (text: string) => JSON.stringify(text);
let fallbacks = 0;
for (const id of Object.keys(names).sort()) {
  const override = OVERRIDES[id];
  const code = override?.code ?? byName.get((names[id] ?? "").toLowerCase());
  if (!code) throw new Error(`No GeoNames country code for market "${id}"`);
  let list = placesFor(code, override?.admin1);
  if (list.length === 0) {
    const capital = capitals.get(code);
    if (!capital) throw new Error(`No places and no capital for market "${id}" (${code})`);
    list = [{ name: capital, population: 0 }];
    fallbacks += 1;
  }
  lines.push(`  ${id}:`);
  for (const place of list) {
    lines.push(`    - { name: ${quote(place.name)}, population: ${place.population} }`);
  }
}
writeFileSync(OUT, `${lines.join("\n")}\n`);
console.log(`Wrote ${OUT}: ${Object.keys(names).length} markets, ${fallbacks} from the capital.`);
