import type {
  AxisId,
  DealDemand,
  DealSlot,
  EscalationLevel,
  GameState,
  Landmark,
  LeagueTierId,
  TimedCountermoveKind,
  TraditionLossReason,
  TraditionType,
  YearlySnapshot,
} from "./types";

// History records (GDD History & Records). Landmarks are the permanent layer: plain facts the
// simulation actually produced, with no text. Stories later read these; they never invent.
// Constructors fix the key order so saved states re-serialize byte-identically.

export const landmarks = {
  leagueFormed: (
    turn: number,
    quarter: number,
    countryId: string,
    reformed: boolean,
  ): Landmark => ({
    kind: "leagueFormed",
    turn,
    quarter,
    countryId,
    reformed,
  }),
  leaguePromoted: (
    turn: number,
    quarter: number,
    countryId: string,
    from: LeagueTierId,
    to: LeagueTierId,
  ): Landmark => ({ kind: "leaguePromoted", turn, quarter, countryId, from, to }),
  leagueSteppedDown: (
    turn: number,
    quarter: number,
    countryId: string,
    from: LeagueTierId,
    to: LeagueTierId,
  ): Landmark => ({ kind: "leagueSteppedDown", turn, quarter, countryId, from, to }),
  leagueFolded: (
    turn: number,
    quarter: number,
    countryId: string,
    leagueTier: LeagueTierId,
  ): Landmark => ({ kind: "leagueFolded", turn, quarter, countryId, leagueTier }),
  anchorCollapse: (
    turn: number,
    quarter: number,
    countryId: string,
    leagueTier: LeagueTierId,
  ): Landmark => ({ kind: "anchorCollapse", turn, quarter, countryId, leagueTier }),
  birthplaceOutlived: (
    turn: number,
    quarter: number,
    countryId: string,
    leagueTier: LeagueTierId,
  ): Landmark => ({ kind: "birthplaceOutlived", turn, quarter, countryId, leagueTier }),
  rankOneTaken: (turn: number, quarter: number): Landmark => ({
    kind: "rankOneTaken",
    turn,
    quarter,
  }),
  rankOneLost: (turn: number, quarter: number, sportId: string): Landmark => ({
    kind: "rankOneLost",
    turn,
    quarter,
    sportId,
  }),
  won: (turn: number, quarter: number, heldTurns: number): Landmark => ({
    kind: "won",
    turn,
    quarter,
    heldTurns,
  }),
  ppTierUp: (turn: number, quarter: number, from: number, to: number): Landmark => ({
    kind: "ppTierUp",
    turn,
    quarter,
    from,
    to,
  }),
  ppTierDown: (turn: number, quarter: number, from: number, to: number): Landmark => ({
    kind: "ppTierDown",
    turn,
    quarter,
    from,
    to,
  }),
  nodeBought: (turn: number, quarter: number, nodeId: string, cost: number): Landmark => ({
    kind: "nodeBought",
    turn,
    quarter,
    nodeId,
    cost,
  }),
  rivalEscalated: (
    turn: number,
    quarter: number,
    countryId: string,
    sportId: string,
    from: EscalationLevel,
    to: EscalationLevel,
  ): Landmark => ({ kind: "rivalEscalated", turn, quarter, countryId, sportId, from, to }),
  rivalDeescalated: (
    turn: number,
    quarter: number,
    countryId: string,
    sportId: string,
    from: EscalationLevel,
    to: EscalationLevel,
  ): Landmark => ({ kind: "rivalDeescalated", turn, quarter, countryId, sportId, from, to }),
  ruleAmended: (
    turn: number,
    quarter: number,
    axis: AxisId,
    from: string,
    to: string,
    demoted: number,
  ): Landmark => ({ kind: "ruleAmended", turn, quarter, axis, from, to, demoted }),
  rivalTournament: (turn: number, quarter: number, sportId: string, year: number): Landmark => ({
    kind: "rivalTournament",
    turn,
    quarter,
    sportId,
    year,
  }),
  rivalCountermove: (
    turn: number,
    quarter: number,
    countryId: string,
    sportId: string,
    move: TimedCountermoveKind,
    endQuarter: number,
  ): Landmark => ({
    kind: "rivalCountermove",
    turn,
    quarter,
    countryId,
    sportId,
    move,
    endQuarter,
  }),
  seasonChampion: (
    turn: number,
    quarter: number,
    countryId: string,
    season: number,
    clubId: number,
  ): Landmark => ({ kind: "seasonChampion", turn, quarter, countryId, season, clubId }),
  starLandmark: (
    kind: "firstStar" | "starRetired",
    turn: number,
    quarter: number,
    countryId: string,
    season: number,
    playerId: number,
    clubId: number,
  ): Landmark => ({ kind, turn, quarter, countryId, season, playerId, clubId }),
  starMoved: (
    turn: number,
    quarter: number,
    countryId: string,
    season: number,
    playerId: number,
    from: number,
    to: number,
    backed: boolean,
  ): Landmark => ({
    kind: "starMoved",
    turn,
    quarter,
    countryId,
    season,
    playerId,
    from,
    to,
    backed,
  }),
  starFinalSeason: (
    turn: number,
    quarter: number,
    countryId: string,
    season: number,
    playerId: number,
    clubId: number,
    backed: boolean,
  ): Landmark => ({
    kind: "starFinalSeason",
    turn,
    quarter,
    countryId,
    season,
    playerId,
    clubId,
    backed,
  }),
  scoringRecord: (
    turn: number,
    quarter: number,
    countryId: string,
    season: number,
    playerId: number,
    scores: number,
  ): Landmark => ({ kind: "scoringRecord", turn, quarter, countryId, season, playerId, scores }),
  starDropped: (
    turn: number,
    quarter: number,
    countryId: string,
    season: number,
    playerId: number,
  ): Landmark => ({ kind: "starDropped", turn, quarter, countryId, season, playerId }),
  traditionBorn: (
    turn: number,
    quarter: number,
    countryId: string,
    traditionId: number,
    type: TraditionType,
  ): Landmark => ({ kind: "traditionBorn", turn, quarter, countryId, traditionId, type }),
  traditionLost: (
    turn: number,
    quarter: number,
    countryId: string,
    traditionId: number,
    type: TraditionType,
    reason: TraditionLossReason,
  ): Landmark => ({ kind: "traditionLost", turn, quarter, countryId, traditionId, type, reason }),
  dealBroken: (
    turn: number,
    quarter: number,
    countryId: string,
    dealId: number,
    partnerId: string,
    slot: DealSlot,
    demand: DealDemand,
    penalty: number,
  ): Landmark => ({
    kind: "dealBroken",
    turn,
    quarter,
    countryId,
    dealId,
    partnerId,
    slot,
    demand,
    penalty,
  }),
  dealEnded: (
    turn: number,
    quarter: number,
    countryId: string,
    dealId: number,
    partnerId: string,
    slot: DealSlot,
  ): Landmark => ({ kind: "dealEnded", turn, quarter, countryId, dealId, partnerId, slot }),
  seatMoved: (
    turn: number,
    quarter: number,
    from: string,
    countryId: string,
    reason: "moved" | "returned",
  ): Landmark => ({ kind: "seatMoved", turn, quarter, from, countryId, reason }),
  rivalRuleCopied: (
    turn: number,
    quarter: number,
    countryId: string,
    sportId: string,
    axis: AxisId,
    from: string,
    to: string,
  ): Landmark => ({ kind: "rivalRuleCopied", turn, quarter, countryId, sportId, axis, from, to }),
};

/**
 * Yearly world snapshot (GDD History & Records): fan buckets for every country × sport, flattened
 * as casual then hardcore, per sport in state order, per country in content order.
 */
export function yearlySnapshot(state: Pick<GameState, "countries">, year: number): YearlySnapshot {
  const fans: number[] = [];
  for (const country of state.countries) {
    for (const sport of country.fans) fans.push(sport.casual, sport.hardcore);
  }
  return { year, fans };
}
